/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as ConsentTokenRouteImport } from './routes/consent.$token'
import { Route as AppTradesRouteImport } from './routes/_app.trades'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProRouteImport } from './routes/_app.pro'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNearRouteImport } from './routes/_app.near'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppDuplicatesRouteImport } from './routes/_app.duplicates'
import { Route as AppAlbumRouteImport } from './routes/_app.album'
import { Route as AppTradeIdRouteImport } from './routes/_app.trade.$id'
import { Route as AppProfileEditRouteImport } from './routes/_app.profile.edit'
import { Route as AppAdminStickersRouteImport } from './routes/_app.admin.stickers'
import { Route as ApiPublicHooksScanMatchAlertsRouteImport } from './routes/api/public/hooks/scan-match-alerts'

const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentTokenRoute = ConsentTokenRouteImport.update({
  id: '/consent/$token',
  path: '/consent/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTradesRoute = AppTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProRoute = AppProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNearRoute = AppNearRouteImport.update({
  id: '/near',
  path: '/near',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppDuplicatesRoute = AppDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AppRoute,
} as any)
const AppAlbumRoute = AppAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeIdRoute = AppTradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppAdminStickersRoute = AppAdminStickersRouteImport.update({
  id: '/admin/stickers',
  path: '/admin/stickers',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksScanMatchAlertsRoute =
  ApiPublicHooksScanMatchAlertsRouteImport.update({
    id: '/api/public/hooks/scan-match-alerts',
    path: '/api/public/hooks/scan-match-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca': typeof SegurancaRoute
  '/album': typeof AppAlbumRoute
  '/duplicates': typeof AppDuplicatesRoute
  '/home': typeof AppHomeRoute
  '/near': typeof AppNearRoute
  '/notifications': typeof AppNotificationsRoute
  '/pro': typeof AppProRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/trades': typeof AppTradesRoute
  '/consent/$token': typeof ConsentTokenRoute
  '/invite/$code': typeof InviteCodeRoute
  '/admin/stickers': typeof AppAdminStickersRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/trade/$id': typeof AppTradeIdRoute
  '/api/public/hooks/scan-match-alerts': typeof ApiPublicHooksScanMatchAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca': typeof SegurancaRoute
  '/album': typeof AppAlbumRoute
  '/duplicates': typeof AppDuplicatesRoute
  '/home': typeof AppHomeRoute
  '/near': typeof AppNearRoute
  '/notifications': typeof AppNotificationsRoute
  '/pro': typeof AppProRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/trades': typeof AppTradesRoute
  '/consent/$token': typeof ConsentTokenRoute
  '/invite/$code': typeof InviteCodeRoute
  '/admin/stickers': typeof AppAdminStickersRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/trade/$id': typeof AppTradeIdRoute
  '/api/public/hooks/scan-match-alerts': typeof ApiPublicHooksScanMatchAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca': typeof SegurancaRoute
  '/_app/album': typeof AppAlbumRoute
  '/_app/duplicates': typeof AppDuplicatesRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/near': typeof AppNearRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pro': typeof AppProRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trades': typeof AppTradesRoute
  '/consent/$token': typeof ConsentTokenRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_app/admin/stickers': typeof AppAdminStickersRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/_app/trade/$id': typeof AppTradeIdRoute
  '/api/public/hooks/scan-match-alerts': typeof ApiPublicHooksScanMatchAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/seguranca'
    | '/album'
    | '/duplicates'
    | '/home'
    | '/near'
    | '/notifications'
    | '/pro'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/trades'
    | '/consent/$token'
    | '/invite/$code'
    | '/admin/stickers'
    | '/profile/edit'
    | '/trade/$id'
    | '/api/public/hooks/scan-match-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/seguranca'
    | '/album'
    | '/duplicates'
    | '/home'
    | '/near'
    | '/notifications'
    | '/pro'
    | '/profile'
    | '/scan'
    | '/settings'
    | '/trades'
    | '/consent/$token'
    | '/invite/$code'
    | '/admin/stickers'
    | '/profile/edit'
    | '/trade/$id'
    | '/api/public/hooks/scan-match-alerts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/seguranca'
    | '/_app/album'
    | '/_app/duplicates'
    | '/_app/home'
    | '/_app/near'
    | '/_app/notifications'
    | '/_app/pro'
    | '/_app/profile'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/trades'
    | '/consent/$token'
    | '/invite/$code'
    | '/_app/admin/stickers'
    | '/_app/profile/edit'
    | '/_app/trade/$id'
    | '/api/public/hooks/scan-match-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SegurancaRoute: typeof SegurancaRoute
  ConsentTokenRoute: typeof ConsentTokenRoute
  InviteCodeRoute: typeof InviteCodeRoute
  ApiPublicHooksScanMatchAlertsRoute: typeof ApiPublicHooksScanMatchAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent/$token': {
      id: '/consent/$token'
      path: '/consent/$token'
      fullPath: '/consent/$token'
      preLoaderRoute: typeof ConsentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trades': {
      id: '/_app/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AppTradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pro': {
      id: '/_app/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AppProRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/near': {
      id: '/_app/near'
      path: '/near'
      fullPath: '/near'
      preLoaderRoute: typeof AppNearRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/duplicates': {
      id: '/_app/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof AppDuplicatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/album': {
      id: '/_app/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AppAlbumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trade/$id': {
      id: '/_app/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof AppTradeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/admin/stickers': {
      id: '/_app/admin/stickers'
      path: '/admin/stickers'
      fullPath: '/admin/stickers'
      preLoaderRoute: typeof AppAdminStickersRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/scan-match-alerts': {
      id: '/api/public/hooks/scan-match-alerts'
      path: '/api/public/hooks/scan-match-alerts'
      fullPath: '/api/public/hooks/scan-match-alerts'
      preLoaderRoute: typeof ApiPublicHooksScanMatchAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAlbumRoute: typeof AppAlbumRoute
  AppDuplicatesRoute: typeof AppDuplicatesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNearRoute: typeof AppNearRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProRoute: typeof AppProRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTradesRoute: typeof AppTradesRoute
  AppAdminStickersRoute: typeof AppAdminStickersRoute
  AppTradeIdRoute: typeof AppTradeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlbumRoute: AppAlbumRoute,
  AppDuplicatesRoute: AppDuplicatesRoute,
  AppHomeRoute: AppHomeRoute,
  AppNearRoute: AppNearRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProRoute: AppProRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTradesRoute: AppTradesRoute,
  AppAdminStickersRoute: AppAdminStickersRoute,
  AppTradeIdRoute: AppTradeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SegurancaRoute: SegurancaRoute,
  ConsentTokenRoute: ConsentTokenRoute,
  InviteCodeRoute: InviteCodeRoute,
  ApiPublicHooksScanMatchAlertsRoute: ApiPublicHooksScanMatchAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
